# Generated by Django 5.1.1 on 2024-10-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_sale_options_sale_quanity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
