# Generated by Django 4.2.16 on 2024-10-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_updated_at_alter_cart_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedproductimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='usedproductimage',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
