# Generated by Django 5.1.1 on 2024-10-19 04:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_usedproductimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedproductimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedproductimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
