services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=shopdee_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - SECRET_KEY=your_secret_key
      - DEBUG=True
      - AWS_ACCESS_KEY_ID=your_aws_access_key
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
      - AWS_STORAGE_BUCKET_NAME=shopdee-image
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: shopdee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
7. ทดสอบการทำงาน