services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: shopdee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/shopdee_db
